### ISSUE TITLE
`vim.bo.expandtab` not working

### ISSUE THREAD

**Issue by GaetanLepage** [icyphox/dotfiles#5]
Does setting this buffer option works for you ?
For me it doesn't (issue explained there: https://github.com/neovim/neovim/issues/12978)

You can reproduce with:
`nvim --headless -u NONE -c "lua vim.bo.smartindent=true" -c "set smartindent?" -c ":e test" -c "set smartindent?" -c "exit"`

Thanks for your great article on this topic !

**Comment by icyphox** [comment]
It does seem to be working, unless I'm testing it wrong. I tried opening a file for which I haven't configured any `ftplugin`, and checked the output of

```
:set expandtab?
```

and it appears to be set.

**Comment by anirudh-deepsource** [comment]
@GaetanLepage you can now use `vim.opt` instead. Works like  `:set`. :)

**Comment by GaetanLepage** [comment]
Thank you ! 
Indeed it works. TJ mentioned this solution here: https://github.com/neovim/neovim/issues/12978

**Comment by icyphox** [comment]
> Thank you ! 
> Indeed it works. TJ mentioned this solution here: https://github.com/neovim/neovim/issues/12978
Awesome, I'll close this now, then. :)


--
Anirudh Oppiliappan
https://icyphox.sh
